[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-js-swc"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "1", features = ["serde-json"] }
napi-derive = { version = "1" }
swc_ecmascript = { version = "0.31.2", features = ["parser", "transforms", "module", "optimization", "react", "typescript", "utils", "visit", "codegen", "utils"] }
swc_ecma_preset_env = { version = "0.15.2" }
swc_common = { version = "0.10.16", features = ["tty-emitter", "sourcemap"] }
swc_atoms = "*"
indoc = "1.0.3"
serde = "1.0.123"
Inflector = "0.11.4"
data-encoding = "2.3.2"
sha-1 = "0.9.4"
dunce = "1.0.1"

[build-dependencies]
napi-build = { version = "1" }
